package com.victor.view;

import javax.swing.JOptionPane;

import com.victor.control.LoginController;
import com.victor.utils.Enigma;

/**
 * @author Wiktor Rosinski
 *
 */
@SuppressWarnings("serial")
public class LoginFrame extends javax.swing.JFrame {

	private LoginController controller;
	
    private javax.swing.JButton buttonLogin;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField textFieldLogin;
    
    
    /**
     * Creates new form LoginFram
     */
    public LoginFrame(LoginController controller) {
    	this.controller=controller;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */                  
    private void initComponents() {

        labelLogin = new javax.swing.JLabel();
        labelPassword = new javax.swing.JLabel();
        textFieldLogin = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        buttonLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Logowanie");
        setResizable(false);

        labelLogin.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        labelLogin.setText("Login:");

        labelPassword.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        labelPassword.setText("Has³o:");

        textFieldLogin.setText("");
        textFieldLogin.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        textFieldLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldLoginActionPerformed(evt);
            }
        });

        passwordField.setText("");
        passwordField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });

        buttonLogin.setText("Zaloguj");
        buttonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonLogin)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(buttonLogin)
                .addGap(35, 35, 35))
        );

        pack();
        setLocation(400, 400);
    }                       

    private void buttonLoginActionPerformed(java.awt.event.ActionEvent evt) {                                            
    	loginProcess();
    }                                           

    private void textFieldLoginActionPerformed(java.awt.event.ActionEvent evt) {                                               
    	loginProcess();
    }                                              

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {                                              
    	loginProcess();
    }       
    
    private void loginProcess(){
//    	System.out.println(textFieldLogin.getText());
//    	System.out.println(Enigma.hashProcess(passwordField.getPassword()));
    	if(!(textFieldLogin.getText().equals("")) && passwordField.getPassword().length>0){
    		if(controller.loginProcess(textFieldLogin.getText(),Enigma.hashProcess(passwordField.getPassword()))){
    			setVisible(false);
    			dispose();
    		}else{
    			JOptionPane.showMessageDialog(this, "B³êdny login lub has³o!", "B³¹d logowania", JOptionPane.ERROR_MESSAGE);
    			textFieldLogin.setText("");
    			passwordField.setText("");
    			textFieldLogin.requestFocusInWindow();
    		}
    	}else{
    		if(textFieldLogin.getText().equals("")){
    			JOptionPane.showMessageDialog(this, "Pole login jest wymagane", "B³¹d walidacji", JOptionPane.ERROR_MESSAGE);
    			textFieldLogin.requestFocusInWindow();
    		} else if(passwordField.getPassword().length<1){
    			JOptionPane.showMessageDialog(this, "Pole has³o jest wymagane", "B³¹d walidacji", JOptionPane.ERROR_MESSAGE);
    			passwordField.requestFocusInWindow();
    		}
    	}
    }

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new LoginFrame().setVisible(true);
//            }
//        });
//    }

                  

                 
}
